/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App.Main;

import App.DAO.PhongDAO;
import App.Entity.Phong;
import App.Impl.PhongDAOImpl;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author WINDOWS
 */
public class TrangChuChung extends javax.swing.JFrame implements TrangChuChungController{
    // ===== DAO & STATE =====
    private final PhongDAO phongDAO = new PhongDAOImpl(); 
    private DefaultTableModel model; 


    public TrangChuChung() {
        initComponents(); 
        init();           
        initTable();       // Tạo bảng phòng trống
        loadPhongTrong(); // phòng trống từ CSDL
            tblPhongTrong.setDefaultEditor(Object.class, null);
    }

    // Hàm khởi tạo ban đầu
    @Override
    public void init() {
        setLocationRelativeTo(null); 
        // Hiện Xin chào
        new xinchaoJdialog(this, true).setVisible(true);
        java.awt.GraphicsEnvironment ge = java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment();
        java.awt.Rectangle usableBounds = ge.getMaximumWindowBounds();
        setBounds(usableBounds);

    }


    // tạo bảng
    private void initTable() {
        model = (DefaultTableModel) tblPhongTrong.getModel(); 
        model.setColumnIdentifiers(new Object[]{
            "Mã phòng", "Diện tích (m²)", "Giá phòng", "Địa chỉ", "Mô tả", "Liên hệ"
        });
        tblPhongTrong.setRowHeight(28); // chiều cao dòng
    }

    // ===== Tải dữ liệu phòng trống từ CSDL =====
    private void loadPhongTrong() {
        model.setRowCount(0); // Xóa hết dữ liệu cũ trong bảng

        try {
            List<Phong> list = phongDAO.findAll(); // Lấy danh sách tất cả phòng

            for (Phong p : list) {
                String trangThai = p.getTrangThai();
                if (trangThai == null) trangThai = "";
                trangThai = trangThai.trim();

                // Kiểm tra nếu phòng trống 
                boolean isTrong = trangThai.equalsIgnoreCase("trống") || trangThai.equals("0");
                if (!isTrong) continue; // Bỏ qua không phải phòng trống

                // Thêm dòng vào bảng
                model.addRow(new Object[]{
                    p.getMaPhong() != null ? p.getMaPhong() : "",
                    p.getDienTich() != null ? p.getDienTich().toString() : "",
                    p.getGiaTien() != null ? p.getGiaTien().toString() : "",
                    p.getDiaChi() != null ? p.getDiaChi() : "",
                    p.getMoTa() != null ? p.getMoTa() : "",
                    p.getLienHe() != null ? p.getLienHe() : ""
                });
            }
        } catch (Exception ex) {
            ex.printStackTrace(); // In lỗi ra console
            JOptionPane.showMessageDialog(this, "Lỗi tải dữ liệu: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhongTrong = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTrangChu = new javax.swing.JMenu();
        jMenuDangnhap = new javax.swing.JMenu();
        jMenuDangky = new javax.swing.JMenu();
        jMenuThoat = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(40, 46, 62));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPhongTrong.setBackground(new java.awt.Color(207, 243, 243));
        tblPhongTrong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblPhongTrong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPhongTrong.setGridColor(new java.awt.Color(255, 255, 255));
        tblPhongTrong.setSelectionBackground(new java.awt.Color(40, 46, 62));
        tblPhongTrong.setSelectionForeground(new java.awt.Color(255, 205, 31));
        tblPhongTrong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhongTrongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhongTrong);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 1190, 450));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("DANH SÁCH PHÒNG TRỐNG");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/nen02.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 760));

        jMenuBar1.setBackground(new java.awt.Color(46, 56, 86));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setName("      "); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(615, 70));

        jMenuTrangChu.setBackground(new java.awt.Color(153, 153, 153));
        jMenuTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/home (1).png"))); // NOI18N
        jMenuTrangChu.setText("Trang chủ");
        jMenuTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuTrangChu.setOpaque(true);
        jMenuTrangChu.setPreferredSize(new java.awt.Dimension(200, 38));
        jMenuBar1.add(jMenuTrangChu);

        jMenuDangnhap.setBackground(new java.awt.Color(153, 153, 153));
        jMenuDangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/Unknown person.png"))); // NOI18N
        jMenuDangnhap.setText("Đăng nhập");
        jMenuDangnhap.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuDangnhap.setOpaque(true);
        jMenuDangnhap.setPreferredSize(new java.awt.Dimension(200, 38));
        jMenuDangnhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuDangnhapMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuDangnhap);

        jMenuDangky.setBackground(new java.awt.Color(153, 153, 153));
        jMenuDangky.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/user.png"))); // NOI18N
        jMenuDangky.setText("Đăng ký");
        jMenuDangky.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuDangky.setOpaque(true);
        jMenuDangky.setPreferredSize(new java.awt.Dimension(200, 38));
        jMenuDangky.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuDangkyMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuDangky);

        jMenuThoat.setBackground(new java.awt.Color(153, 153, 153));
        jMenuThoat.setBorder(null);
        jMenuThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/logout.png"))); // NOI18N
        jMenuThoat.setText("Thoát");
        jMenuThoat.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuThoat.setOpaque(true);
        jMenuThoat.setPreferredSize(new java.awt.Dimension(200, 32));
        jMenuThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuThoatMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuThoat);

        jMenu2.setBackground(new java.awt.Color(153, 153, 153));
        jMenu2.setOpaque(true);
        jMenu2.setPreferredSize(new java.awt.Dimension(900, 6));
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1560, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuThoatMouseClicked
        // TODO add your handling code here:
        int c = JOptionPane.showConfirmDialog(this, "Bạn muốn thoát ứng dụng?", "Thoát",
                JOptionPane.YES_NO_OPTION);
        if (c == JOptionPane.YES_OPTION) System.exit(0);
    }//GEN-LAST:event_jMenuThoatMouseClicked

    private void tblPhongTrongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhongTrongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPhongTrongMouseClicked

    private void jMenuDangnhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuDangnhapMouseClicked
        // TODO add your handling code here: 
        // Đóng cửa sổ hiện tại
        this.dispose();
        this.showdangnhapJDialog(this); 
    }//GEN-LAST:event_jMenuDangnhapMouseClicked

    private void jMenuDangkyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuDangkyMouseClicked
        // TODO add your handling code here:
         this.showdangkyJDialog(this); 
    }//GEN-LAST:event_jMenuDangkyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                // có màu FlatLaf Light - ko màu Nimbus
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            } 
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuChung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuChung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuChung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuChung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuChung().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDangky;
    private javax.swing.JMenu jMenuDangnhap;
    private javax.swing.JMenu jMenuThoat;
    private javax.swing.JMenu jMenuTrangChu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPhongTrong;
    // End of variables declaration//GEN-END:variables

}
// poso diS